fix(requirements): revert beanie v2.0.0 upgrade due to errors raised
"""
discord.app_commands.errors.CommandInvokeError: Command '{command}'
raised an exception: TypeError: object AsyncIOMotorLatentCommandCursor
can't be used in 'await' expression
"""