fix(requirements): revert `beanie v2.0.0` upgrade due to exceptions (#223)
## Description

Reverted the Beanie v2.0.0 upgrade that was causing exceptions:

> discord.app_commands.errors.CommandInvokeError: Command '{command}'
raised an exception: TypeError: object AsyncIOMotorLatentCommandCursor
can't be used in 'await' expression

For the moment, this change will be reverted and the exceptions will be
addressed before re-upgrading beanie.